set_property SRC_FILE_INFO {cfile:/home/anshul/fpga/bitfilegeneration/constraint/KC705_TOP.xdc rfile:../../../../constraint/KC705_TOP.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/anshul/fpga/bitfilegeneration/tcl250/.Xil/Vivado-8734-AJIT6/dcp/PCIeGen1x8If64_in_context.xdc rfile:../dcp/PCIeGen1x8If64_in_context.xdc id:2 order:EARLY scoped_inst:PCIeGen1x8If64_i} [current_design]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports PCIE_RESET_N]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports PCIE_RESET_N]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G25 [get_ports PCIE_RESET_N]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports {LED[0]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports {LED[1]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports {LED[2]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports {LED[3]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB8 [get_ports {LED[0]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports {LED[1]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC9 [get_ports {LED[2]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB9 [get_ports {LED[3]}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells PCIeGen1x8If64_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {test_channels[0].module1/interface0/cpu_to_riffa_q/dual_clock_fifo}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {test_channels[0].module1/interface0/riffa_to_cpu_q/dual_clock_fifo}]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.000 -name PCIeGen1x8If64_i/user_clk_out [get_pins PCIeGen1x8If64_i/user_clk_out]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.000 -name pcie_refclk [get_pins refclk_ibuf/O]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_ports [list {LED[3]} {LED[2]} {LED[1]} {LED[0]}]]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports PCIE_RESET_N]
