# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-8734-AJIT6/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7k325tffg900-2

    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -include /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl {
      /PCIeGen1x8If64_stub.v
      /fifo_generator_0_stub.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/reorder_queue_output.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/riffa.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/rotate.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_data_fifo.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/scsdpram.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_port_monitor_32.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/fifo.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/txr_engine_ultrascale.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/rx_port_channel_gate.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_port_buffer_32.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/sg_list_reader_64.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/async_fifo.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/rx_engine_ultrascale.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_multiplexer_64.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/rx_port_64.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/rx_engine_classic.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/ram_1clk_1w_1r.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_data_shift.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/sg_list_requester.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_port_64.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/interrupt.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/sync_fifo.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/rx_port_reader.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_data_pipeline.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/registers.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/sg_list_reader_128.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/rxc_engine_128.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/translation_xilinx.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/rxr_engine_128.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/interrupt_controller.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/pipeline.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_port_channel_gate_128.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/demux.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/counter.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/txc_engine_ultrascale.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/translation_altera.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/channel.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/one_hot_mux.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_engine_classic.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_port_buffer_64.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/fifo_packer_128.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/fifo_packer_32.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/channel_64.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_multiplexer_128.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/sg_list_reader_32.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_port_writer.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/cross_domain_signal.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/rx_port_32.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/reset_extender.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/syncff.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_engine.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_port_monitor_64.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/async_fifo_fwft.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_engine_selector.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/rxr_engine_ultrascale.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/mux.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/channel_32.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/ram_2clk_1w_1r.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/rxc_engine_classic.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_port_monitor_128.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_port_channel_gate_64.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/reset_controller.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_hdr_fifo.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_multiplexer_32.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/txc_engine_classic.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/txr_engine_classic.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/reorder_queue_input.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_multiplexer.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_alignment_pipeline.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/channel_128.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_port_128.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/rx_port_128.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_engine_ultrascale.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/fifo_packer_64.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/reorder_queue.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_port_32.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/offset_to_mask.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/register.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/rxc_engine_ultrascale.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/offset_flag_to_one_hot.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/rx_port_requester_mux.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/engine_layer.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/ff.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/rxr_engine_classic.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_port_channel_gate_32.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/recv_credit_flow_ctrl.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/shiftreg.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_hdl/tx_port_buffer_128.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/chnl_tester.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_wrapper_kc705.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/riffa_cpu_bridge.v
      /home/anshul/fpga/bitfilegeneration/hdl_250/KC705_Gen1x8If64.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      /home/anshul/fpga/bitfilegeneration/hdl_250/DualClockedQueue.vhdl
      /home/anshul/fpga/bitfilegeneration/ahir_files/aes_v1/ahir_system_global_package.vhdl
      /home/anshul/fpga/bitfilegeneration/ahir_files/aes_v1/ahir_system.vhdl
    }
      rt::read_vhdl -lib aHiR_ieee_proposed /home/anshul/AHIR/ahir/release/vhdl/aHiR_ieee_proposed.vhdl
      rt::read_vhdl -lib ahir /home/anshul/AHIR/ahir/release/vhdl/ahir.vhdl
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-8734-AJIT6/realtime/KC705_Gen1x8If64_synth.xdc
    rt::sdcChecksum
    set rt::top KC705_Gen1x8If64
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-8734-AJIT6/"
    if {$rt::useElabCache == false} {
      rt::run_synthesis -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
